# Generated by Django 2.2.5 on 2021-04-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUDIEE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_item',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
