# Generated by Django 2.2.5 on 2021-04-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUDIEE', '0002_food_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
