# Generated by Django 3.2 on 2021-04-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUDIEE', '0004_auto_20210421_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
