# Generated by Django 3.2 on 2021-04-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUDIEE', '0006_item_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='featured_dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='FUDIEE/images')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='food_item',
            name='img',
            field=models.ImageField(upload_to='FUDIEE/images'),
        ),
    ]
